swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        "200":
          description: A paged array of pets
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
  /outlierProteins:
    get:
      summary: List of proteins of interest
      operationId: listProteins
      tags:
        - proteins
      responses:
        "200":
          description: A paged array of proteins
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
